name: 'Boost Prebuild With Mac'

on: workflow_dispatch

env:
  OutputBranchName: mactestlido
  BoostDownloadURL: https://boostorg.jfrog.io/artifactory/main/release/1.81.0/source/boost_1_81_0.tar.bz2

jobs:
  Prebuild-Boost:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Initialize mandatory git config
        run: |
          git config user.name "A.J. Orians"
          git config user.email ajorians@gmail.com
      - name: Create release branch
        run: git checkout -b $OutputBranchName
      - name: Download
        run: wget "$BoostDownloadURL"
      - name: Extract Download file
        run: |
          tar --bzip2 -xf boost_1_81_0.tar.bz2
          rm boost_1_81_0.tar.bz2
      - name: Bootstrap Boost
        run: |
          cd boost_1_81_0
          ls
          ./bootstrap.sh --prefix=.
          cd boost_1_81_0
          ls
      - name: Build MacOS Silicon Boost
        run: |
          ./b2 install architecture=arm address-model=64 target-os=darwin --clean --prefix=macosarm --with-atomic --with-chrono --with-date_time --with-filesystem --with-program_options --with-regex --with-serialization --with-system --with-thread
          ls
      - name: Build MacOS Boost
        run: |
          ./b2 install architecture=x86 address-model=64 target-os=darwin --clean --prefix=macos --with-atomic --with-chrono --with-date_time --with-filesystem --with-program_options --with-regex --with-serialization --with-system --with-thread
          ls
      - name: Prepare Includes
        run: |
          ls
          mkdir include
          mv boost_1_81_0/boost include
          git add include
          git commit --message "Added Includes :)"
      - name: Prepare Libs
        run: |
          ls boost_1_81_0/lib
          mkdir lib
          mv boost_1_81_0/lib/libboost_atomic*.a lib
          mv boost_1_81_0/lib/libboost_chrono*.a lib
          mv boost_1_81_0/lib/libboost_date_time*.a lib
          mv boost_1_81_0/lib/libboost_filesystem*.a lib
          mv boost_1_81_0/lib/libboost_program_options*.a lib
          mv boost_1_81_0/lib/libboost_regex*.a lib
          mv boost_1_81_0/lib/libboost_serialization*.a lib
          mv boost_1_81_0/lib/libboost_system*.a lib
          mv boost_1_81_0/lib/libboost_thread*.a lib
          git add lib
          git commit --message "Added Libs :)"
      - name: Push new branch
        run: git push origin $OutputBranchName
