name: 'Boost Prebuild With Mac'

on: workflow_dispatch

env:
  OutputBranchName: mactestlido
  BoostDownloadURL: https://boostorg.jfrog.io/artifactory/main/release/1.81.0/source/boost_1_81_0.tar.bz2

jobs:
  Prebuild-Boost:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Initialize mandatory git config
        run: |
          git config user.name "A.J. Orians"
          git config user.email ajorians@gmail.com
      - name: Create release branch
        run: git checkout -b $OutputBranchName
      - name: Download
        run: wget "$BoostDownloadURL"
      - name: Extract Download file
        run: |
          tar --bzip2 -xf boost_1_81_0.tar.bz2
          rm boost_1_81_0.tar.bz2
      - name: Bootstrap Boost
        run: |
          cd boost_1_81_0
          ls
          ./bootstrap.sh --prefix=.
      - name: Build MacOS Silicon Boost
        run: |
          cd boost_1_81_0
          ls
          ./b2 install architecture=arm address-model=64 target-os=darwin --prefix=macosarm --with-atomic --with-chrono --with-date_time --with-filesystem --with-program_options --with-regex --with-serialization --with-system --with-thread
          ls
      - name: Build MacOS Boost
        run: |
          cd boost_1_81_0
          ls
          ./b2 install architecture=x86 address-model=64 target-os=darwin --prefix=macos --with-atomic --with-chrono --with-date_time --with-filesystem --with-program_options --with-regex --with-serialization --with-system --with-thread
          ls
      - name: Combine architecture
        run: |
          mkdir lib
          lipo -arch x86_64 boost_1_81_0/macos/lib/libboost_atomic.a -arch arm64 boost_1_81_0/macosarm/lib/libboost_atomic.a -create -output lib/libboost_atomic.a
          lipo -arch x86_64 boost_1_81_0/macos/lib/libboost_chrono.a -arch arm64 boost_1_81_0/macosarm/lib/libboost_chrono.a -create -output lib/libboost_chrono.a
          lipo -arch x86_64 boost_1_81_0/macos/lib/libboost_date_time.a -arch arm64 boost_1_81_0/macosarm/lib/libboost_date_time.a -create -output lib/libboost_date_time.a
          lipo -arch x86_64 boost_1_81_0/macos/lib/libboost_filesystem.a -arch arm64 boost_1_81_0/macosarm/lib/libboost_filesystem.a -create -output lib/libboost_filesystem.a
          lipo -arch x86_64 boost_1_81_0/macos/lib/libboost_program_options.a -arch arm64 boost_1_81_0/macosarm/lib/libboost_program_options.a -create -output lib/libboost_program_options.a
          lipo -arch x86_64 boost_1_81_0/macos/lib/libboost_regex.a -arch arm64 boost_1_81_0/macosarm/lib/libboost_regex.a -create -output lib/libboost_regex.a
          lipo -arch x86_64 boost_1_81_0/macos/lib/libboost_serialization.a -arch arm64 boost_1_81_0/macosarm/lib/libboost_serialization.a -create -output lib/libboost_serialization.a
          lipo -arch x86_64 boost_1_81_0/macos/lib/libboost_system.a -arch arm64 boost_1_81_0/macosarm/lib/libboost_system.a -create -output lib/libboost_system.a
          lipo -arch x86_64 boost_1_81_0/macos/lib/libboost_thread.a -arch arm64 boost_1_81_0/macosarm/lib/libboost_thread.a -create -output lib/libboost_thread.a
      - name: Prepare Includes
        run: |
          ls
          mkdir include
          mv boost_1_81_0/boost include
          git add include
          git commit --message "Added Includes :)"
      - name: Prepare Libs
        run: |
          git add lib
          git commit --message "Added Libs :)"
      - name: Push new branch
        run: git push origin $OutputBranchName
