name: 'Boost Prebuild With MSVC'

#on: workflow_dispatch

on:
  push:
    branches:
      - master
env:
  BoostDownloadURL: http://test.orians.org/boost_test.zip

jobs:
  Prebuild-Boost:
    runs-on: windows-latest
    env:
      ZipName: boost
    steps:
      - name: Download
        shell: powershell
        run: Invoke-WebRequest -Uri "$env:BoostDownloadURL" -OutFile "$env:ZipName.zip"
      - name: Extract Zip file
        shell: cmd
        run: |
          7z x -y %ZipName%.zip
          del %ZIPname%.zip
      - name: CD into extracted directory
        shell: cmd
        run: |
          cd boost_test
          dir
          cd boost_test
          dir
      - name: Bootstrap Boost Build
        shell: cmd
        run: |
          bootstrap
