name: 'Boost Prebuild With MSVC'

on: workflow_dispatch

env:
  BoostVersion: 1.81.0
  BoostVersionExtractedFolder: boost_1_81_0
  OutputBranchName: release142/1.81.0
  BoostDownloadURL: http://test.orians.org/boost_1_81_0.zip
  
jobs:
  Prebuild-Boost:
    runs-on: windows-latest
    env:
      ZipName: boost
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Initialize mandatory git config
        run: |
          git config user.name "A.J. Orians"
          git config user.email ajorians@gmail.com
      - name: Create release branch
        run: git checkout -b $env:OutputBranchName
      - name: Download
        shell: powershell
        run: Invoke-WebRequest -Uri "$env:BoostDownloadURL" -OutFile "$env:ZipName.zip"
      - name: Extract Zip file
        shell: cmd
        run: |
          7z x -y %ZipName%.zip
          del %ZIPname%.zip
      - name: Bootstrap Boost
        shell: cmd
        run: |
          cd $env:BoostVersionExtractedFolder
          dir
          bootstrap
      - name: Build Boost
        shell: cmd
        run: |
          cd $env:BoostVersionExtractedFolder
          dir
          .\b2 toolset=msvc-14.2 address-model=64 --with-atomic --with-chrono --with-date_time --with-filesystem --with-program_options --with-regex --with-serialization --with-system --with-thread
      - name: Prepare Includes
        run: |
          dir
          mkdir include
          move $env:BoostVersionExtractedFolder\boost include
          git add include
          git commit --message "Added Includes :)"
      - name: Prepare Libs
        run: |
          dir
          mkdir lib
          mkdir lib\x64
          mkdir lib\x64\Release
          move $env:BoostVersionExtractedFolder\stage\lib\libboost_atomic-vc*-mt-x64-* lib\x64\Release
          move $env:BoostVersionExtractedFolder\stage\lib\libboost_chrono-vc*-mt-x64-* lib\x64\Release
          move $env:BoostVersionExtractedFolder\stage\lib\libboost_date_time-vc*-mt-x64-* lib\x64\Release
          move $env:BoostVersionExtractedFolder\stage\lib\libboost_filesystem-vc*-mt-x64-* lib\x64\Release
          move $env:BoostVersionExtractedFolder\stage\lib\libboost_program_options-vc*-mt-x64-* lib\x64\Release
          move $env:BoostVersionExtractedFolder\stage\lib\libboost_regex-vc*-mt-x64-* lib\x64\Release
          move $env:BoostVersionExtractedFolder\stage\lib\libboost_serialization-vc*-mt-x64-* lib\x64\Release
          move $env:BoostVersionExtractedFolder\stage\lib\libboost_system-vc*-mt-x64-* lib\x64\Release
          move $env:BoostVersionExtractedFolder\stage\lib\libboost_thread-vc*-mt-x64-* lib\x64\Release
          mkdir lib\x64\Debug
          move $env:BoostVersionExtractedFolder\stage\lib\libboost_atomic-vc*-mt-gd-x64-* lib\x64\Debug
          move $env:BoostVersionExtractedFolder\stage\lib\libboost_chrono-vc*-mt-gd-x64-* lib\x64\Debug
          move $env:BoostVersionExtractedFolder\stage\lib\libboost_date_time-vc*-mt-gd-x64-* lib\x64\Debug
          move $env:BoostVersionExtractedFolder\stage\lib\libboost_filesystem-vc*-mt-gd-x64-* lib\x64\Debug
          move $env:BoostVersionExtractedFolder\stage\lib\libboost_program_options-vc*-mt-gd-x64-* lib\x64\Debug
          move $env:BoostVersionExtractedFolder\stage\lib\libboost_regex-vc*-mt-gd-x64-* lib\x64\Debug
          move $env:BoostVersionExtractedFolder\stage\lib\libboost_serialization-vc*-mt-gd-x64-* lib\x64\Debug
          move $env:BoostVersionExtractedFolder\stage\lib\libboost_system-vc*-mt-gd-x64-* lib\x64\Debug
          move $env:BoostVersionExtractedFolder\stage\lib\libboost_thread-vc*-mt-gd-x64-* lib\x64\Debug
          git add lib
          git commit --message "Added Libs :)"
      - name: Push new branch
        run: git push origin $env:OutputBranchName
